name: TypeScript Build Check

on:
  workflow_call:
    inputs:
      runs-on:
        # https://github.com/orgs/community/discussions/26801
        description: 'Type of machine of job to run on. Needs to be quoted, because to support self-hosted labels and inputs does not support Array nor multiple types (default: "ubuntu-latest")'
        type: string
        default: '"ubuntu-latest"'
        required: false

jobs:
  build:
    runs-on: ${{ fromJson(inputs.runs-on) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: .node-version
          cache: "pnpm"
          check-latest: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run TypeScript build
        run: pnpm run build
